### PR TITLE
62 Add images to DB

### PR DESCRIPTION
**Pull request by AlphaLEXray**
PR for Issue #62

### CODE REVIEW

**Comment by AlphaLEXray** [comment]
The PNG and GIF tests complete successfully locally but freeze when they are executed in the GitHub Action.

**Comment by AlphaLEXray** [comment]
Bruno has issues when there are around 5 or more POST request with images.

**Comment by AlphaLEXray** [comment]
@Niko4u5 Does the image endpoint need to support PUT requests? Personally I don't see the use for it.

**Comment by Niko4u5** [comment]
> @Niko4u5 Does the image endpoint need to support PUT requests? Personally I don't see the use for it.

I dont think it is necessary

**Review by Timplayer — APPROVED** [review]

**Pull request merged**
